name: Build & Tests
on: [push, pull_request]
jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.5.app
      - name: Start server
        run: |
          python Tests/wsserver/ExampleWSServer.py 8443 secure &
          python Tests/wsserver/ExampleWSServer.py 8000 &
      - name: Build and Test SPM
        run: swift test
      - name: Update Cocoa Pods repo
        run: pod repo update
      - name: Build and Test CocoaPods
        run: pod lib lint --allow-warnings --fail-fast
  linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.4
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --security-opt apparmor=unconfined
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install python
        run: apt-get update && apt-get install -y python2.7 python-openssl
      - name: Start server & Build & Test
        run: |
          python2.7 Tests/wsserver/ExampleWSServer.py 8443 secure &
          python2.7 Tests/wsserver/ExampleWSServer.py 8000 &
          swift test
