name: Publish CocoaPods package
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.2.app
      - name: Start server
        run: |
          python Tests/wsserver/ExampleWSServer.py 8443 secure &
          python Tests/wsserver/ExampleWSServer.py 8000 &
      - name: Publish Pod
        run: pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
